- name: put /root/k8s-rabbitmq-ha-config.yaml
  template: src=k8s-rabbitmq-ha-config.yaml dest=/root/k8s-rabbitmq-ha-config.yaml

- name: create /data/pvs
  file: dest=/data/pvs state=directory owner=root mode=0600

- name: put a rabbitmq-ha-pv1.yaml file
  template: src=pv1.yaml dest=/root/rabbitmq-ha-pv1.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ rabbitmq_ha_cluster_namespace }} | grep rabbitmq-ha-data-1
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ rabbitmq_ha_cluster_namespace }} -f /root/rabbitmq-ha-pv1.yaml
  when: result|failed

- name: put a rabbitmq-ha-pv2.yaml file
  template: src=pv2.yaml dest=/root/rabbitmq-ha-pv2.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ rabbitmq_ha_cluster_namespace }} | grep rabbitmq-ha-data-2
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ rabbitmq_ha_cluster_namespace }} -f /root/rabbitmq-ha-pv2.yaml
  when: result|failed

- name: put a rabbitmq-ha-pv3.yaml file
  template: src=pv3.yaml dest=/root/rabbitmq-ha-pv3.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ rabbitmq_ha_cluster_namespace }} | grep rabbitmq-ha-data-3
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ rabbitmq_ha_cluster_namespace }} -f /root/rabbitmq-ha-pv3.yaml
  when: result|failed

- name: check if a Helm release for rabbitmq-ha-cluster is present
  shell: helm list --namespace={{ rabbitmq_ha_cluster_namespace }} | grep rabbitmq-ha-cluster-release
  register: result
  ignore_errors: true

- name: enable the incubator repo
  shell: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/

  #- name: clone the repo
  #  git: repo=https://github.com/alexclear/charts.git dest=/root/charts

- name: install a RabbitMQ HA cluster using a Helm chart
  shell: cd /root/charts/stable && helm install -f /root/k8s-rabbitmq-ha-config.yaml rabbitmq-ha --namespace {{ rabbitmq_ha_cluster_namespace }} --name rabbitmq-ha-cluster-release
  when: result|failed
