kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-ha-data-3
  labels:
    type: local
spec:
  storageClassName: rabbitmqha
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pvs/rabbitmq-ha-pv-3"
